name: realtime_crypto

# services:
  # notifier:
  #   build:
  #     context: ./services/notifier
  #   container_name: notifier
  #   depends_on:
  #     - kafka
  #   environment:
  #     - KAFKA_BROKER=kafka:29092
  #     - TELEGRAM_TOKEN=8767281878:AAGahCNd3_zrjmrj5JW595kFKc_aFmgz-l0 
  #     - TELEGRAM_CHAT_ID=6630100534 
  #   networks:
  #     - net

include:
  - ./deployment/docker-compose.kafka.yml
  - ./deployment/docker-compose.spark.yml
  - ./deployment/docker-compose.postgre.yml
  - ./deployment/docker-compose.redis.yml

networks:
  net:
    driver: bridge

volumes:
  kafka-data:
  postgres-data:
  redis-data: