name: realtime_crypto

services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - redis
      - postgres
    environment:
      - KAFKA_BROKER_INTERNAL=kafka:29092
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=whale_alert
    volumes:
      - ./services/api:/app
      - ./utils:/app/utils
      - ./services/font-end:/app/font-end
    networks:
      - net

  notifier:
    build:
      context: ./services/notifier
      dockerfile: Dockerfile.bot
    container_name: notifier
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./services/notifier:/app
      - ./utils:/app/utils
    networks:
      - net

include:
  - ./deployment/docker-compose.kafka.yml
  - ./deployment/docker-compose.spark.yml
  - ./deployment/docker-compose.postgre.yml
  - ./deployment/docker-compose.redis.yml

networks:
  net:
    driver: bridge

volumes:
  kafka-data:
  postgres-data:
  redis-data: